name: Sms balance check service

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Development Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v3

      - name: Create environment file and update variable from secrets
        run: |
          cp .env.example .env
          sed -i '/PORT/d' .env
          sed -i '/SLACK_WEB_HOOK_URL/d' .env
          sed -i '/SSL_WIRELESS_API_TOKEN/d' .env
          sed -i '/SSL_WIRELESS_CSMS_IDS/d' .env

          echo 'PORT=${{ secrets.APP_PORT }}' >> .env
          echo 'SLACK_WEB_HOOK_URL=${{ secrets.SLACK_WEB_HOOK_URL }}' >> .env
          echo 'SSL_WIRELESS_API_TOKEN=${{ secrets.SSL_WIRELESS_API_TOKEN }}' >> .env
          echo 'SSL_WIRELESS_CSMS_IDS=${{ secrets.SSL_WIRELESS_CSMS_IDS }}' >> .env
        shell: bash

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      #Login to Docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:latest

  deploy:
    name: Development deploy process
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Development Server Access via SSH Access
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /              
            docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY_NAME }} )
            docker rm $(docker ps -a --filter "status=exited" -q)
            docker pull ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY_NAME }}
            docker run -d -p 3031:3000 --name ${{ secrets.DOCKER_REPOSITORY_NAME }} ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY_NAME }}
