name: Sms balance check service

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Development Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v3

      - name: Create environment file and update variable from secrets
        run: |
          cp .env.example .env
          sed -i '/PORT/d' .env
          sed -i '/SLACK_WEB_HOOK_URL/d' .env
          sed -i '/SSL_WIRELESS_API_TOKEN/d' .env
          sed -i '/SSL_WIRELESS_CSMS_IDS/d' .env

          echo 'PORT=${{ secrets.APP_PORT }}' >> .env
          echo 'SLACK_WEB_HOOK_URL=${{ secrets.SLACK_WEB_HOOK_URL }}' >> .env
          echo 'SSL_WIRELESS_API_TOKEN=${{ secrets.SSL_WIRELESS_API_TOKEN }}' >> .env
          echo 'SSL_WIRELESS_CSMS_IDS=${{ secrets.SSL_WIRELESS_CSMS_IDS }}' >> .env
        shell: bash

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}:latest
